[package]
name = "hello_cairo"
version = "0.1.0"
edition = "2024_07"
main = "src/entering_cairset.cairo"
# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
